management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - application/json
  tomcat:
    connection-timeout: 60000
    uri-encoding: UTF-8
  servlet:
    context-path: /
    application-display-name: Demo Spring.
spring:
  profiles:
    active: '@spring.active.profile@'
logging:
  level:
    root: INFO
    com:
      example: INFO
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      fileNamePattern: logs/application-%d{yyyy-MM-dd}.%i.log
      maxHistory: 30
      maxFileSize: 10MB
springdoc:
  swagger-ui:
      path: /swagger-ui.html