apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot-service
spec:
  type: NodePort
  selector:
    app: demo-spring-boot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30003
