apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-boot
  labels:
    app: demo-spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-spring-boot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: demo-spring-boot
    spec:
      containers:
        - name: demo-spring-boot
          image: rcarcamo/demo-spring-boot:efbc98e15f59c6f03c3f2338244e5e16c23ff30c
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-secret

