name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del c贸digo fuente
      - name: Checkout c贸digo
        uses: actions/checkout@v3

      # 2. Cache de Maven para acelerar builds
      - name: Cache de Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 3. Configurar JDK 17
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # 4. Construir el proyecto con Maven
      - name: Construir con Maven
        run: mvn clean package -DskipTests

      # 5. Ejecutar pruebas unitarias (opcional)
      - name: Ejecutar pruebas con Maven
        run: mvn test

      # 6. Configurar QEMU (para multi-arch builds)
      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v2

      # 7. Configurar Docker Buildx
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 8. Iniciar sesi贸n en Docker Hub
      - name: Iniciar sesi贸n en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 9. Construir y etiquetar la imagen Docker
      - name: Construir y etiquetar la imagen Docker
        id: build-image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/demo-spring-boot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/demo-spring-boot:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

      # 10. Salida de la imagen construida
      - name: Salida de la imagen
        run: echo 'Imagen construida y enviada a Docker Hub: ${{ secrets.DOCKERHUB_USERNAME }}/demo-spring-boot:latest'
