name: PR Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout código
        uses: actions/checkout@v3

      # 2. Cache de Maven para acelerar builds
      - name: Cache de Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 3. Configurar JDK 17
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # 4. Construir el proyecto con Maven
      - name: Construir con Maven
        run: mvn clean package -DskipTests

      # 5. Ejecutar pruebas unitarias
      - name: Ejecutar pruebas con Maven
        run: mvn test